### ISSUE TITLE
Fix divideByZero Warning in AimdCongestionController

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#296]
Currently in `AimdCongestionController`, if `detailsAmountReceived` is 0, then the WARNING below will  be emitted.

Instead, we should check for this case and just directly call `halvePrepareAmount(prepareAmount);` so we don't get this warning in this case.

```
WARNING: Unable to decode AmountTooLargeErrorData from F08 Reject packet. Setting newMaxPacketAmount to be half the prepare amount. rejectPacket=InterledgerRejectPacket{, code=InterledgerErrorCode{code='F08', name='AMOUNT TOO LARGE', errorFamily=F}, triggeredBy=Optional[InterledgerAddress{value=test.operator}], message=the error, data=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=} error={}
java.lang.ArithmeticException: / by zero
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4106)
	at java.math.BigDecimal.divide(BigDecimal.java:5198)
	at java.math.BigDecimal.divide(BigDecimal.java:1561)
	at java.math.BigDecimal.divide(BigDecimal.java:1641)
	at org.interledger.stream.sender.AimdCongestionController.handleF08Rejection(AimdCongestionController.java:240)
	at org.interledger.stream.sender.AimdCongestionControllerTest.handleF08RejectionWithGarbageData(AimdCongestionControllerTest.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by sappenin** [comment]
Fixed via #299
