### ISSUE TITLE
Handle `LinkException` in StreamSender

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#300]
When something goes wrong with the `Link` in the `StreamSender`, a `LinkeException` will be propagated from the Link.

We should handle this gracefully in the StreamSender, likely by triggering a graceful timeout.

For an example StackTrace, see here:

```bash
Sep 27, 2019 3:47:06 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Creating container for image: nhartner/interledgerrs-standalone:latest
Sep 27, 2019 3:47:06 PM org.testcontainers.utility.RegistryAuthLocator runCredentialProvider
INFO: Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
Sep 27, 2019 3:47:06 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Starting container with ID: a801db9689621bb8136e57b1f79eaa02980551beb43fde3e6218fe79e9965627
Sep 27, 2019 3:47:07 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Container nhartner/interledgerrs-standalone:latest is starting: a801db9689621bb8136e57b1f79eaa02980551beb43fde3e6218fe79e9965627
Sep 27, 2019 3:47:08 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Container nhartner/interledgerrs-standalone:latest started
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: --> POST http://localhost:32861/accounts (264-byte body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK http://localhost:32861/accounts (54ms, unknown-length body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: --> POST http://localhost:32861/accounts (292-byte body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK http://localhost:32861/accounts (6ms, unknown-length body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: --> POST http://localhost:32861/accounts (264-byte body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK http://localhost:32861/accounts (6ms, unknown-length body)
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: --> GET http://localhost:32861/spsp/accountTest1000000
Sep 27, 2019 3:47:09 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK http://localhost:32861/spsp/accountTest1000000 (4ms, unknown-length body)
Sep 27, 2019 3:47:14 PM org.interledger.stream.sender.SimpleStreamSender$SendMoneyAggregator lambda$send$1
SEVERE: Failed to send full amount
Sep 27, 2019 3:47:14 PM okhttp3.internal.platform.Platform log
INFO: --> POST http://localhost:32861/ilp (184-byte body)
Sep 27, 2019 3:47:14 PM okhttp3.internal.platform.Platform log
INFO: <-- 401 Unauthorized http://localhost:32861/ilp (6ms, unknown-length body)
Sep 27, 2019 3:47:14 PM org.interledger.link.http.IlpOverHttpLink parseThrowableProblem
WARNING: Unable to parse Ilp-over-Http response. preparePacket=InterledgerPreparePacket{, amount=0, expiresAt=2019-09-27T21:47:44.175Z, executionCondition=Condition{hash=4F8JsOW8Kifwq9WMIZzCxgj7i88g6wRfvcqwJNeIHxo=}, destination=InterledgerAddress{value=test.xpring-dev.rs1.accountTest1000000.jbY_arRGmtosPH9UqxFLoGHE6OlLbVfSvGV8tpBtSHI}, data=s58r3EF8rWXGkFH6ZHVbPmA0FlMvDqLqoqzALSlINt9O6B313ZmDrA==} errorResponseBody= exception={}
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at org.interledger.link.http.IlpOverHttpLink.parseThrowableProblem(IlpOverHttpLink.java:260)
	at org.interledger.link.http.IlpOverHttpLink.sendPacket(IlpOverHttpLink.java:132)
	at org.interledger.stream.sender.SimpleStreamSender$SendMoneyAggregator.closeConnection(SimpleStreamSender.java:605)
	at org.interledger.stream.sender.SimpleStreamSender$SendMoneyAggregator.lambda$send$2(SimpleStreamSender.java:290)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1595)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)




java.util.concurrent.CompletionException: org.interledger.link.exceptions.LinkException: Unable to connect to remote ILP-over-HTTP Link: Invalid Bearer Token. response=Response{protocol=http/1.1, code=401, message=Unauthorized, url=http://localhost:32861/ilp}

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1595)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.interledger.link.exceptions.LinkException: Unable to connect to remote ILP-over-HTTP Link: Invalid Bearer Token. response=Response{protocol=http/1.1, code=401, message=Unauthorized, url=http://localhost:32861/ilp}
	at org.interledger.link.http.IlpOverHttpLink.sendPacket(IlpOverHttpLink.java:139)
	at org.interledger.stream.sender.SimpleStreamSender$SendMoneyAggregator.closeConnection(SimpleStreamSender.java:605)
	at org.interledger.stream.sender.SimpleStreamSender$SendMoneyAggregator.lambda$send$2(SimpleStreamSender.java:290)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 9 more
```

**Comment by sappenin** [comment]
For context, this error manifests when the unit test shuts down (and kills the connector server) before the threads finish. 

While this is a flaw in how testes were running previously (now fixed) we should try to replicate this behavior in a Left/Right test in order to make sure the sender can handle this properly.

**Comment by sappenin** [comment]
StreamSender has been deprecated in-favor of [ILP Pay](https://github.com/hyperledger/quilt/tree/df/ilp-pay) functionality. Closing this.
